### ISSUE TITLE
Project name could not be inferred

### ISSUE THREAD

**Issue by ferenczy** [shroudedcode/devstats#10]
No matter what I'm doing, the only output from devstats is the following error:

    Error: Project name could not be inferred. Please specify the `projectName` option.

`devstats`, `devstats add <url>`, everything produces such error.

After a short investigation, it looks like the `conf` package cannot find the `package.json` file, see for example [here](https://github.com/ngx-rocket/generator-ngx-rocket/issues/421).

Windows 7 Ultimate 64-bit
Node.js 11.0.0
npm 6.4.1

**Comment by niklashigi** [comment]
@ferenczy I just released a new version. Let me know if it fixes your issue.

**Comment by ferenczy** [comment]
Looks good, thanks!
