### ISSUE TITLE
Devstats for private repos?

### ISSUE THREAD

**Issue by johnhayesio** [shroudedcode/devstats#14]
The tool doesn't seem to show private repo commits. Is there a way to enable that?

**Comment by niklashigi** [comment]
Turning on "Private contributions" on your profile should make them show up in devstats:

![](https://user-images.githubusercontent.com/29176678/98274083-4bf60500-1f93-11eb-90e7-4a01eb85251f.png)

It seems like you've already enabled this option on your own account, so it should work.
Are you talking about a different account or have you only enabled this option after trying out devstats? :thinking:

**Comment by niklashigi** [comment]
@johnhayesio Can I close this issue?

**Comment by johnhayesio** [comment]
@shroudedcode Of course. No problem!

**Comment by johnhayesio** [comment]
Thanks by the way!
