### ISSUE TITLE
github stats issue

### ISSUE THREAD

**Issue by pawlos** [shroudedcode/devstats#15]
Noticed that github stats return an error. It looks like the structure has changed and it's no longer queryable by `.day` selector. The new one is `.ContributionCalendar-day`.

![image](https://user-images.githubusercontent.com/1296768/118394961-19b31780-b648-11eb-8597-0b8018bb2edc.png)

**Comment by pawlos** [comment]
The error can be solved the in the following way

accounts\github.ts inside `getReport`
```
const date = dayElement.getAttribute('data-date');
if (date !== null) {
    this.contributions.set(
      getDayIndex(M((date as string).trim())),
      parseInt(dayElement.getAttribute('data-count') as string, 10),
     ) 
}
```

**Comment by niklashigi** [comment]
This is fixed now, thanks for reporting!
