### ISSUE TITLE
Terminal is painted entirely

### ISSUE THREAD

**Issue by DinoSourcesRex** [shroudedcode/devstats#7]
So this happens both on Git Bash and Powershell (Windows 10) for me.

I've installed globally with `yarn global add devstats`, added a few accounts and anytime I run `devstats` I get the screen below.

![powershell_2018-11-15_01-52-17](https://user-images.githubusercontent.com/4295028/48522496-30126980-e879-11e8-8675-0600d0983f00.png)

Any ideas?

**Comment by niklashigi** [comment]
I was able to reproduce your issue and find out what causes it: Windows somehow requires a full style reset to "end" background colors. That's why the background color "bleeds out" of the area its supposed to fill. I added a full style reset in #8 and will release a version with a fix soon.

**Comment by DinoSourcesRex** [comment]
@shroudedcode Thanks for the quick response! Looking forward to the fix.

**Comment by niklashigi** [comment]
@DinoSourcesRex No problem, thank you for reporting the issue. I might have never found it myself since I don't use Windows for programming.

Can you update `devstats` and check whether the fix works for you?

**Comment by DinoSourcesRex** [comment]
@shroudedcode I upgraded and checked both Git Bash and Powershell and both work as expected.

Thanks so much.

**Comment by niklashigi** [comment]
@DinoSourcesRex I'm happy I was able to solve your issue. :grinning: Mind giving the repo a star? :star2:

**Comment by DinoSourcesRex** [comment]
@shroudedcode Surprised I hadn't done it already!
